// Mozilla User Preferences

// DO NOT EDIT THIS FILE.
//
// If you make changes to this file while the application is running,
// the changes will be overwritten when the application exits.
//
// To change a preference value, you can either:
// - modify it via the UI (e.g. via about:config in the browser); or
// - set it within a user.js file in your profile.

user_pref("app.normandy.first_run", false);
user_pref("app.normandy.migrationsApplied", 7);
user_pref("app.normandy.user_id", "3f926d27-7c69-4e21-8a77-20499a70a9f7");
user_pref("app.update.lastUpdateTime.addon-background-update-timer", 1575486796);
user_pref("app.update.lastUpdateTime.blocklist-background-update-timer", 1575486916);
user_pref("app.update.lastUpdateTime.browser-cleanup-thumbnails", 1575456212);
user_pref("app.update.lastUpdateTime.recipe-client-addon-run", 1575486556);
user_pref("app.update.lastUpdateTime.search-engine-update-timer", 1575456332);
user_pref("app.update.lastUpdateTime.services-settings-poll-changes", 1575486676);
user_pref("app.update.lastUpdateTime.telemetry_modules_ping", 1575487156);
user_pref("app.update.lastUpdateTime.xpi-signature-verification", 1575487036);
user_pref("browser.bookmarks.restore_default_bookmarks", false);
user_pref("browser.cache.disk.amount_written", 7603);
user_pref("browser.cache.disk.capacity", 768000);
user_pref("browser.cache.disk.filesystem_reported", 1);
user_pref("browser.contentblocking.category", "standard");
user_pref("browser.download.panel.shown", true);
user_pref("browser.laterrun.bookkeeping.profileCreationTime", 1575456183);
user_pref("browser.laterrun.bookkeeping.sessionCount", 3);
user_pref("browser.laterrun.enabled", true);
user_pref("browser.migration.version", 87);
user_pref("browser.newtabpage.activity-stream.impressionId", "{4e0d1f9c-e04f-4602-8376-76a3d5d7dcc4}");
user_pref("browser.newtabpage.storageVersion", 1);
user_pref("browser.pageActions.persistedActions", "{\"version\":1,\"ids\":[\"bookmark\",\"pinTab\",\"bookmarkSeparator\",\"copyURL\",\"emailLink\",\"addSearchEngine\",\"sendToDevice\",\"pocket\",\"screenshots_mozilla_org\"],\"idsInUrlbar\":[\"pocket\",\"bookmark\"]}");
user_pref("browser.pagethumbnails.storage_version", 3);
user_pref("browser.safebrowsing.provider.google4.lastupdatetime", "1575486537248");
user_pref("browser.safebrowsing.provider.google4.nextupdatetime", "1575488361248");
user_pref("browser.safebrowsing.provider.mozilla.lastupdatetime", "1575486541016");
user_pref("browser.safebrowsing.provider.mozilla.nextupdatetime", "1575490141016");
user_pref("browser.search.region", "ZA");
user_pref("browser.sessionstore.upgradeBackup.latestBuildID", "20191031085722");
user_pref("browser.slowStartup.averageTime", 12511);
user_pref("browser.slowStartup.samples", 3);
user_pref("browser.startup.homepage_override.buildID", "20191031085722");
user_pref("browser.startup.homepage_override.mstone", "70.0.1");
user_pref("browser.startup.lastColdStartupCheck", 1575486530);
user_pref("browser.uiCustomization.state", "{\"placements\":{\"widget-overflow-fixed-list\":[],\"nav-bar\":[\"back-button\",\"forward-button\",\"stop-reload-button\",\"home-button\",\"customizableui-special-spring1\",\"urlbar-container\",\"customizableui-special-spring2\",\"downloads-button\",\"library-button\",\"sidebar-button\",\"fxa-toolbar-menu-button\"],\"toolbar-menubar\":[\"menubar-items\"],\"TabsToolbar\":[\"tabbrowser-tabs\",\"new-tab-button\",\"alltabs-button\"],\"PersonalToolbar\":[\"personal-bookmarks\"]},\"seen\":[\"developer-button\"],\"dirtyAreaCache\":[\"nav-bar\",\"toolbar-menubar\",\"TabsToolbar\",\"PersonalToolbar\"],\"currentVersion\":16,\"newElementCount\":2}");
user_pref("browser.urlbar.placeholderName", "Google");
user_pref("datareporting.policy.dataSubmissionPolicyAcceptedVersion", 2);
user_pref("datareporting.policy.dataSubmissionPolicyNotifiedTime", "1575456190926");
user_pref("distribution.canonical.bookmarksProcessed", true);
user_pref("distribution.iniFile.exists.appversion", "70.0.1");
user_pref("distribution.iniFile.exists.value", true);
user_pref("dom.push.userAgentID", "53c795d10c91414a980246ac8c1440fd");
user_pref("extensions.activeThemeID", "default-theme@mozilla.org");
user_pref("extensions.blocklist.lastModified", "Tue, 03 Dec 2019 12:43:01 GMT");
user_pref("extensions.blocklist.pingCountTotal", 2);
user_pref("extensions.blocklist.pingCountVersion", 2);
user_pref("extensions.databaseSchema", 31);
user_pref("extensions.getAddons.cache.lastUpdate", 1575486802);
user_pref("extensions.getAddons.databaseSchema", 5);
user_pref("extensions.incognito.migrated", true);
user_pref("extensions.lastAppBuildId", "20191031085722");
user_pref("extensions.lastAppVersion", "70.0.1");
user_pref("extensions.lastPlatformVersion", "70.0.1");
user_pref("extensions.pendingOperations", false);
user_pref("extensions.systemAddonSet", "{\"schema\":1,\"addons\":{}}");
user_pref("extensions.webcompat.perform_injections", true);
user_pref("extensions.webcompat.perform_ua_overrides", true);
user_pref("extensions.webextensions.ExtensionStorageIDB.migrated.screenshots@mozilla.org", true);
user_pref("extensions.webextensions.uuids", "{\"formautofill@mozilla.org\":\"64432d9a-d6e4-4080-ae5c-698d0ed285f7\",\"screenshots@mozilla.org\":\"292e7da0-7ed9-455c-aa3a-0c86d3f7f8a0\",\"webcompat-reporter@mozilla.org\":\"2d578323-0928-4cac-bbb8-cf766083eefa\",\"webcompat@mozilla.org\":\"eb338ab2-db51-472e-a133-db6147bb683d\",\"default-theme@mozilla.org\":\"19e58393-a478-4a38-9f25-70a84db3826a\",\"google@search.mozilla.org\":\"7a68b060-c9ab-41b9-9b63-666cf0216d8e\",\"amazondotcom@search.mozilla.org\":\"1938aeb3-bb4d-4925-bc9e-c2f35476d7e9\",\"bing@search.mozilla.org\":\"2cd85c09-7881-4a4e-ba2f-25f9706fce2c\",\"ddg@search.mozilla.org\":\"5b06e2e1-ab13-4b38-b4be-34a5566b5871\",\"ebay@search.mozilla.org\":\"8fe3f3a3-2946-4c05-82b1-423f71093af9\",\"twitter@search.mozilla.org\":\"441d7760-7f72-4667-8c06-f91d976b4e9b\",\"wikipedia@search.mozilla.org\":\"caec5f46-4fa2-4555-84d1-93d3840b21fd\"}");
user_pref("gfx.blacklist.layers.opengl", 4);
user_pref("gfx.blacklist.layers.opengl.failureid", "FEATURE_FAILURE_SOFTWARE_GL");
user_pref("identity.fxaccounts.toolbar.accessed", true);
user_pref("media.gmp-gmpopenh264.abi", "x86_64-gcc3");
user_pref("media.gmp-gmpopenh264.lastUpdate", 1575456286);
user_pref("media.gmp-gmpopenh264.version", "1.8.1.1");
user_pref("media.gmp-manager.buildID", "20191031085722");
user_pref("media.gmp-manager.lastCheck", 1575456279);
user_pref("media.gmp.storage.version.observed", 1);
user_pref("network.predictor.cleaned-up", true);
user_pref("pdfjs.enabledCache.state", true);
user_pref("pdfjs.migrationVersion", 2);
user_pref("pdfjs.previousHandler.alwaysAskBeforeHandling", true);
user_pref("pdfjs.previousHandler.preferredAction", 4);
user_pref("places.history.expiration.transient_current_max_pages", 96637);
user_pref("privacy.sanitize.pending", "[]");
user_pref("security.sandbox.content.tempDirSuffix", "8f700168-32db-4d48-b8d5-04778808fe0d");
user_pref("security.sandbox.plugin.tempDirSuffix", "7b6c8ba3-c99a-4981-9be1-966c958ac4a4");
user_pref("services.blocklist.pinning.checked", 1575486884);
user_pref("services.settings.clock_skew_seconds", -208);
user_pref("services.settings.last_etag", "\"1575485467436\"");
user_pref("services.settings.last_update_seconds", 1575486884);
user_pref("services.settings.main.anti-tracking-url-decoration.last_check", 1575486884);
user_pref("services.settings.main.cfr-fxa.last_check", 1575486884);
user_pref("services.settings.main.cfr.last_check", 1575486884);
user_pref("services.settings.main.fxmonitor-breaches.last_check", 1575486884);
user_pref("services.settings.main.hijack-blocklists.last_check", 1575486884);
user_pref("services.settings.main.language-dictionaries.last_check", 1575486884);
user_pref("services.settings.main.normandy-recipes.last_check", 1575486884);
user_pref("services.settings.main.public-suffix-list.last_check", 1575486884);
user_pref("services.settings.main.sites-classification.last_check", 1575486884);
user_pref("services.settings.main.url-classifier-skip-urls.last_check", 1575486884);
user_pref("services.settings.main.whats-new-panel.last_check", 1575486884);
user_pref("services.settings.security.onecrl.checked", 1575486884);
user_pref("signon.importedFromSqlite", true);
user_pref("toolkit.startup.last_success", 1575486519);
user_pref("toolkit.telemetry.cachedClientID", "a813d4ca-e21d-43b9-a257-a4dbd4da745a");
user_pref("toolkit.telemetry.previousBuildID", "20191031085722");
user_pref("toolkit.telemetry.reportingpolicy.firstRun", false);
user_pref("trailhead.extendedTriplets.experiment", "control");
user_pref("trailhead.firstrun.didSeeAboutWelcome", true);
